// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Challenge from the server used to guarantee freshness of attestations
public struct Challenge: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name for this Challenge in the format
  /// `projects/*/locations/*/challenges/*`
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which this Challenge was created
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which this Challenge will no longer be usable. It
  /// is also the expiration time for any tokens generated from this Challenge.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Indicates if this challenge has been used to generate a token.
  public var used: Swift.Bool = Swift.Bool()

  /// Output only. Identical to nonce, but as a string.
  public var tpmNonce: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Challenge`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Challenge().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let used = CodingKeys(stringValue: "used")
    static let tpmNonce = CodingKeys(stringValue: "tpmNonce")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "expireTime",
      "used",
      "tpmNonce",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .expireTime)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .used) {
      self.used = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tpmNonce) {
      self.tpmNonce = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.expireTime, forKey: .expireTime)
    try container.encode(self.used, forKey: .used)
    try container.encode(self.tpmNonce, forKey: .tpmNonce)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.Challenge"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
