// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ConfidentialComputingLogging: ConfidentialComputingStub {
    let inner: any ConfidentialComputingStub
    let logger: Logger

    public init(_ inner: any ConfidentialComputingStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-confidentialcomputing-v1"
      logger[metadataKey: "gcp.client.service"] = "confidentialcomputing"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ConfidentialComputing"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createChallenge(
      request: CreateChallengeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.Challenge {
      try await self._intercept(
        request: request,
        options: options,
        name: "createChallenge",
        action: {
          (r: CreateChallengeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.Challenge
          in
          return try await self.inner.createChallenge(request: r, options: o)
        })
    }

    public func verifyAttestation(
      request: VerifyAttestationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyAttestation",
        action: {
          (r: VerifyAttestationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse
          in
          return try await self.inner.verifyAttestation(request: r, options: o)
        })
    }

    public func verifyConfidentialSpace(
      request: VerifyConfidentialSpaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyConfidentialSpace",
        action: {
          (r: VerifyConfidentialSpaceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse
          in
          return try await self.inner.verifyConfidentialSpace(request: r, options: o)
        })
    }

    public func verifyConfidentialGke(
      request: VerifyConfidentialGkeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "verifyConfidentialGke",
        action: {
          (r: VerifyConfidentialGkeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse
          in
          return try await self.inner.verifyConfidentialGke(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
