// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ConfidentialComputingRetry: ConfidentialComputingStub {
    let inner: any ConfidentialComputingStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any ConfidentialComputingStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createChallenge(
      request: CreateChallengeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.Challenge {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateChallengeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.Challenge
          in
          return try await self.inner.createChallenge(request: r, options: o)
        })
    }

    public func verifyAttestation(
      request: VerifyAttestationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyAttestationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse
          in
          return try await self.inner.verifyAttestation(request: r, options: o)
        })
    }

    public func verifyConfidentialSpace(
      request: VerifyConfidentialSpaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyConfidentialSpaceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse
          in
          return try await self.inner.verifyConfidentialSpace(request: r, options: o)
        })
    }

    public func verifyConfidentialGke(
      request: VerifyConfidentialGkeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: VerifyConfidentialGkeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse
          in
          return try await self.inner.verifyConfidentialGke(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
