// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol ConfidentialComputingStub: Sendable {
    func createChallenge(
      request: CreateChallengeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.Challenge

    func verifyAttestation(
      request: VerifyAttestationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse

    func verifyConfidentialSpace(
      request: VerifyConfidentialSpaceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse

    func verifyConfidentialGke(
      request: VerifyConfidentialGkeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
