// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "ConfidentialComputingQuickstart")
public class ConfidentialComputingClient: Clients.ConfidentialComputingProtocol {
  let inner: any Clients.ConfidentialComputingStub

  /// Creates a new `ConfidentialComputingClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConfidentialComputingStub = try Clients.ConfidentialComputingTransport(
      options)
    inner = Clients.ConfidentialComputingRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConfidentialComputingLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new Challenge in a given project and location.
  ///
  /// @Snippet(path: "ConfidentialComputing_CreateChallenge")
  public func createChallenge(
    request: CreateChallengeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.Challenge {
    try await self.inner.createChallenge(request: request, options: options)
  }

  /// Verifies the provided attestation info, returning a signed attestation
  /// token.
  ///
  /// @Snippet(path: "ConfidentialComputing_VerifyAttestation")
  public func verifyAttestation(
    request: VerifyAttestationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse {
    try await self.inner.verifyAttestation(request: request, options: options)
  }

  /// Verifies whether the provided attestation info is valid, returning a signed
  /// attestation token if so.
  ///
  /// @Snippet(path: "ConfidentialComputing_VerifyConfidentialSpace")
  public func verifyConfidentialSpace(
    request: VerifyConfidentialSpaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse {
    try await self.inner.verifyConfidentialSpace(request: request, options: options)
  }

  /// Verifies the provided Confidential GKE attestation info, returning a signed
  /// OIDC token.
  ///
  /// @Snippet(path: "ConfidentialComputing_VerifyConfidentialGke")
  public func verifyConfidentialGke(
    request: VerifyConfidentialGkeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse {
    try await self.inner.verifyConfidentialGke(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "ConfidentialComputing_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "ConfidentialComputing_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "ConfidentialComputing_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConfidentialComputingClient`.
  ///
  /// To mock `ConfidentialComputingClient` change your functions to receive
  /// `some ConfidentialComputingProtocol` or `any ConfidentialComputingProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConfidentialComputingProtocol {
    /// See `ConfidentialComputingClient.createChallenge`.
    func createChallenge(request: CreateChallengeRequest) async throws
      -> GoogleCloudConfidentialComputingV1.Challenge

    /// See `ConfidentialComputingClient.createChallenge`.
    func createChallenge(
      parent: Swift.String,
      challenge: Challenge?,
    ) async throws -> GoogleCloudConfidentialComputingV1.Challenge

    /// See `ConfidentialComputingClient.verifyAttestation`.
    func verifyAttestation(request: VerifyAttestationRequest) async throws
      -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse

    /// See `ConfidentialComputingClient.verifyConfidentialSpace`.
    func verifyConfidentialSpace(request: VerifyConfidentialSpaceRequest) async throws
      -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse

    /// See `ConfidentialComputingClient.verifyConfidentialGke`.
    func verifyConfidentialGke(request: VerifyConfidentialGkeRequest) async throws
      -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse

    /// See `ConfidentialComputingClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConfidentialComputingClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ConfidentialComputingClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `ConfidentialComputingClient.createChallenge`.
    func createChallenge(
      request: CreateChallengeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.Challenge

    /// See `ConfidentialComputingClient.verifyAttestation`.
    func verifyAttestation(
      request: VerifyAttestationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse

    /// See `ConfidentialComputingClient.verifyConfidentialSpace`.
    func verifyConfidentialSpace(
      request: VerifyConfidentialSpaceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse

    /// See `ConfidentialComputingClient.verifyConfidentialGke`.
    func verifyConfidentialGke(
      request: VerifyConfidentialGkeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse

    /// See `ConfidentialComputingClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConfidentialComputingClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `ConfidentialComputingClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.ConfidentialComputingProtocol {
  public func createChallenge(request: CreateChallengeRequest) async throws
    -> GoogleCloudConfidentialComputingV1.Challenge
  {
    try await self.createChallenge(request: request, options: .init())
  }

  public func createChallenge(
    request: CreateChallengeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.Challenge {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createChallenge(
    parent: Swift.String,
    challenge: Challenge?,
  ) async throws -> GoogleCloudConfidentialComputingV1.Challenge {
    let request = CreateChallengeRequest().with {
      $0.parent = parent
      $0.challenge = challenge
    }
    return try await self.createChallenge(request: request)
  }

  public func verifyAttestation(request: VerifyAttestationRequest) async throws
    -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse
  {
    try await self.verifyAttestation(request: request, options: .init())
  }

  public func verifyAttestation(
    request: VerifyAttestationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyAttestationResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func verifyConfidentialSpace(request: VerifyConfidentialSpaceRequest) async throws
    -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse
  {
    try await self.verifyConfidentialSpace(request: request, options: .init())
  }

  public func verifyConfidentialSpace(
    request: VerifyConfidentialSpaceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialSpaceResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func verifyConfidentialGke(request: VerifyConfidentialGkeRequest) async throws
    -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse
  {
    try await self.verifyConfidentialGke(request: request, options: .init())
  }

  public func verifyConfidentialGke(
    request: VerifyConfidentialGkeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudConfidentialComputingV1.VerifyConfidentialGkeResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
