// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An Nvidia attestation report for GPU and NVSwitch devices.
/// Contains necessary attestation evidence that the client collects for
/// verification.
public struct NvidiaAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Confidential Computing feature that the attestation is for.
  public var ccFeature: OneOf_CcFeature? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NvidiaAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NvidiaAttestation().with { $0.spt = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let spt = CodingKeys(stringValue: "spt")
    static let ppcie = CodingKeys(stringValue: "ppcie")
    static let mpt = CodingKeys(stringValue: "mpt")

    static let _knownKeys: Set<Swift.String> = [
      "spt",
      "ppcie",
      "mpt",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var ccFeature: OneOf_CcFeature? = nil
    let ccFeatureCheckAndSet = {
      if ccFeature != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'ccFeature'"))
      }
      ccFeature = $0
    }
    if let spt = try container.decodeIfPresent(
      NvidiaAttestation.SinglePassthroughAttestation?.self, forKey: .spt)
    {
      try ccFeatureCheckAndSet(.spt(spt))
    }
    if let ppcie = try container.decodeIfPresent(
      NvidiaAttestation.ProtectedPcieAttestation?.self, forKey: .ppcie)
    {
      try ccFeatureCheckAndSet(.ppcie(ppcie))
    }
    if let mpt = try container.decodeIfPresent(
      NvidiaAttestation.MultiGpuSecurePassthroughAttestation?.self, forKey: .mpt)
    {
      try ccFeatureCheckAndSet(.mpt(mpt))
    }
    self.ccFeature = ccFeature
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.ccFeature {
      switch choice {
      case .spt(let value):
        try container.encode(value, forKey: .spt)
      case .ppcie(let value):
        try container.encode(value, forKey: .ppcie)
      case .mpt(let value):
        try container.encode(value, forKey: .mpt)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// GpuInfo contains the attestation evidence for a GPU device.
  public struct GpuInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The UUID of the GPU device.
    public var uuid: Swift.String = Swift.String()

    /// Optional. The driver version of the GPU.
    public var driverVersion: Swift.String = Swift.String()

    /// Optional. The vBIOS version of the GPU.
    public var vbiosVersion: Swift.String = Swift.String()

    /// Optional. The GPU architecture type.
    public var gpuArchitectureType: NvidiaAttestation.GpuArchitectureType =
      NvidiaAttestation.GpuArchitectureType()

    /// Optional. The raw attestation certificate chain for the GPU device.
    public var attestationCertificateChain: Foundation.Data = Foundation.Data()

    /// Optional. The raw attestation report for the GPU device.
    /// This field contains SPDM request/response defined in
    /// https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.0.pdf
    public var attestationReport: Foundation.Data = Foundation.Data()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GpuInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GpuInfo().with { $0.uuid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uuid = CodingKeys(stringValue: "uuid")
      static let driverVersion = CodingKeys(stringValue: "driverVersion")
      static let vbiosVersion = CodingKeys(stringValue: "vbiosVersion")
      static let gpuArchitectureType = CodingKeys(stringValue: "gpuArchitectureType")
      static let attestationCertificateChain = CodingKeys(
        stringValue: "attestationCertificateChain")
      static let attestationReport = CodingKeys(stringValue: "attestationReport")

      static let _knownKeys: Set<Swift.String> = [
        "uuid",
        "driverVersion",
        "vbiosVersion",
        "gpuArchitectureType",
        "attestationCertificateChain",
        "attestationReport",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uuid) {
        self.uuid = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .driverVersion) {
        self.driverVersion = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vbiosVersion) {
        self.vbiosVersion = value
      }
      if let value = try container.decodeIfPresent(
        NvidiaAttestation.GpuArchitectureType.self, forKey: .gpuArchitectureType)
      {
        self.gpuArchitectureType = value
      }
      if let value = try container.decodeIfPresent(
        Foundation.Data.self, forKey: .attestationCertificateChain)
      {
        self.attestationCertificateChain = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .attestationReport)
      {
        self.attestationReport = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uuid, forKey: .uuid)
      try container.encode(self.driverVersion, forKey: .driverVersion)
      try container.encode(self.vbiosVersion, forKey: .vbiosVersion)
      try container.encode(self.gpuArchitectureType, forKey: .gpuArchitectureType)
      try container.encode(self.attestationCertificateChain, forKey: .attestationCertificateChain)
      try container.encode(self.attestationReport, forKey: .attestationReport)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation.GpuInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// SwitchInfo contains the attestation evidence for a NVSwitch device.
  public struct SwitchInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The UUID of the NVSwitch device.
    public var uuid: Swift.String = Swift.String()

    /// Optional. The raw attestation certificate chain for the NVSwitch device.
    public var attestationCertificateChain: Foundation.Data = Foundation.Data()

    /// Optional. The raw attestation report for the NvSwitch device.
    /// This field contains SPDM request/response defined in
    /// https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.0.pdf
    public var attestationReport: Foundation.Data = Foundation.Data()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SwitchInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SwitchInfo().with { $0.uuid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uuid = CodingKeys(stringValue: "uuid")
      static let attestationCertificateChain = CodingKeys(
        stringValue: "attestationCertificateChain")
      static let attestationReport = CodingKeys(stringValue: "attestationReport")

      static let _knownKeys: Set<Swift.String> = [
        "uuid",
        "attestationCertificateChain",
        "attestationReport",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uuid) {
        self.uuid = value
      }
      if let value = try container.decodeIfPresent(
        Foundation.Data.self, forKey: .attestationCertificateChain)
      {
        self.attestationCertificateChain = value
      }
      if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .attestationReport)
      {
        self.attestationReport = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uuid, forKey: .uuid)
      try container.encode(self.attestationCertificateChain, forKey: .attestationCertificateChain)
      try container.encode(self.attestationReport, forKey: .attestationReport)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation.SwitchInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Single GPU Passthrough (SPT) attestation.
  public struct SinglePassthroughAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Single GPU quote.
    public var gpuQuote: NvidiaAttestation.GpuInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SinglePassthroughAttestation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SinglePassthroughAttestation().with { $0.gpuQuote = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gpuQuote = CodingKeys(stringValue: "gpuQuote")

      static let _knownKeys: Set<Swift.String> = [
        "gpuQuote"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.gpuQuote = try container.decodeIfPresent(
        NvidiaAttestation.GpuInfo.self, forKey: .gpuQuote)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.gpuQuote, forKey: .gpuQuote)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation.SinglePassthroughAttestation"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Protected PCIe (PPCIE) attestation.
  /// Eight Hopper GPUs with Four NVSwitch Passthrough.
  public struct ProtectedPcieAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A list of GPU infos.
    public var gpuQuotes: [NvidiaAttestation.GpuInfo] = []

    /// Optional. A list of SWITCH infos.
    public var switchQuotes: [NvidiaAttestation.SwitchInfo] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ProtectedPcieAttestation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ProtectedPcieAttestation().with { $0.gpuQuotes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gpuQuotes = CodingKeys(stringValue: "gpuQuotes")
      static let switchQuotes = CodingKeys(stringValue: "switchQuotes")

      static let _knownKeys: Set<Swift.String> = [
        "gpuQuotes",
        "switchQuotes",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [NvidiaAttestation.GpuInfo].self, forKey: .gpuQuotes)
      {
        self.gpuQuotes = value
      }
      if let value = try container.decodeIfPresent(
        [NvidiaAttestation.SwitchInfo].self, forKey: .switchQuotes)
      {
        self.switchQuotes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.gpuQuotes, forKey: .gpuQuotes)
      try container.encode(self.switchQuotes, forKey: .switchQuotes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation.ProtectedPcieAttestation"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// MultiGpuSecurePassthroughAttestation contains the attestation evidence
  /// for a Multi-GPU Secure Passthrough (MPT) attestation.
  public struct MultiGpuSecurePassthroughAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. A list of GPU quotes.
    public var gpuQuotes: [NvidiaAttestation.GpuInfo] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MultiGpuSecurePassthroughAttestation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MultiGpuSecurePassthroughAttestation().with { $0.gpuQuotes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gpuQuotes = CodingKeys(stringValue: "gpuQuotes")

      static let _knownKeys: Set<Swift.String> = [
        "gpuQuotes"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [NvidiaAttestation.GpuInfo].self, forKey: .gpuQuotes)
      {
        self.gpuQuotes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.gpuQuotes, forKey: .gpuQuotes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation.MultiGpuSecurePassthroughAttestation"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// GpuArchitectureType enumerates the supported GPU architecture types.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum GpuArchitectureType: Codable, Equatable, Sendable {
    /// Unspecified GPU architecture type.
    case unspecified
    /// Hopper GPU architecture type.
    case hopper
    /// Blackwell GPU architecture type.
    case blackwell
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hopper: return 8
      case .blackwell: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "GPU_ARCHITECTURE_TYPE_UNSPECIFIED"
      case .hopper: return "GPU_ARCHITECTURE_TYPE_HOPPER"
      case .blackwell: return "GPU_ARCHITECTURE_TYPE_BLACKWELL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GpuArchitectureType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "GPU_ARCHITECTURE_TYPE_UNSPECIFIED": self = .unspecified
      case "GPU_ARCHITECTURE_TYPE_HOPPER": self = .hopper
      case "GPU_ARCHITECTURE_TYPE_BLACKWELL": self = .blackwell
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GpuArchitectureType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 8: self = .hopper
      case 10: self = .blackwell
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("GPU_ARCHITECTURE_TYPE_UNSPECIFIED")
      case .hopper: return try container.encode("GPU_ARCHITECTURE_TYPE_HOPPER")
      case .blackwell: return try container.encode("GPU_ARCHITECTURE_TYPE_BLACKWELL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The Confidential Computing feature that the attestation is for.
  public enum OneOf_CcFeature: Codable, Equatable, Sendable {
    /// Single GPU Passthrough (SPT) attestation.
    indirect case spt(NvidiaAttestation.SinglePassthroughAttestation?)
    /// Protected PCIe (PPCIE) attestation.
    indirect case ppcie(NvidiaAttestation.ProtectedPcieAttestation?)
    /// Multi-GPU Secure Passthrough (MPT) attestation.
    indirect case mpt(NvidiaAttestation.MultiGpuSecurePassthroughAttestation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.NvidiaAttestation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
