// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An SEV-SNP Attestation Report.
/// Contains the attestation report and the certificate bundle that the client
/// collects.
public struct SevSnpAttestation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The SEV-SNP Attestation Report
  /// Format is in revision 1.55, §7.3 Attestation, Table 22. ATTESTATION_REPORT
  /// Structure in this document:
  /// https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf
  public var report: Foundation.Data = Foundation.Data()

  /// Optional. Certificate bundle defined in the GHCB protocol definition
  /// Format is documented in GHCB revision 2.03, section 4.1.8.1 struct
  /// cert_table in this document:
  /// https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56421.pdf
  public var auxBlob: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SevSnpAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SevSnpAttestation().with { $0.report = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let report = CodingKeys(stringValue: "report")
    static let auxBlob = CodingKeys(stringValue: "auxBlob")

    static let _knownKeys: Set<Swift.String> = [
      "report",
      "auxBlob",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .report) {
      self.report = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .auxBlob) {
      self.auxBlob = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.report, forKey: .report)
    try container.encode(self.auxBlob, forKey: .auxBlob)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.SevSnpAttestation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
