// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An SEV-SNP Attestation Report.
/// Contains the attestation report and the certificate bundle that the client
/// collects.
public struct SevSnpAttestation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The SEV-SNP Attestation Report
  /// Format is in revision 1.55, §7.3 Attestation, Table 22. ATTESTATION_REPORT
  /// Structure in this document:
  /// https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56860.pdf
  public var report: Foundation.Data = Foundation.Data()

  /// Optional. Certificate bundle defined in the GHCB protocol definition
  /// Format is documented in GHCB revision 2.03, section 4.1.8.1 struct
  /// cert_table in this document:
  /// https://www.amd.com/content/dam/amd/en/documents/epyc-technical-docs/specifications/56421.pdf
  public var auxBlob: Foundation.Data = Foundation.Data()

  /// Initialize a new instance of `SevSnpAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SevSnpAttestation().with { $0.report = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.SevSnpAttestation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
