// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A TDX Attestation quote.
public struct TdxCcelAttestation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The Confidential Computing Event Log (CCEL) ACPI table. Formatted
  /// as described in the ACPI Specification 6.5.
  public var ccelAcpiTable: Foundation.Data = Foundation.Data()

  /// Optional. The CCEL event log. Formatted as described in the UEFI 2.10.
  public var ccelData: Foundation.Data = Foundation.Data()

  /// Optional. An Event Log containing additional events measured into the RTMR
  /// that are not already present in the CCEL.
  public var canonicalEventLog: Foundation.Data = Foundation.Data()

  /// Optional. The TDX attestation quote from the guest. It contains the RTMR
  /// values.
  public var tdQuote: Foundation.Data = Foundation.Data()

  /// Initialize a new instance of `TdxCcelAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TdxCcelAttestation().with { $0.ccelAcpiTable = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TdxCcelAttestation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
