// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A TDX Attestation quote.
public struct TdxCcelAttestation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The Confidential Computing Event Log (CCEL) ACPI table. Formatted
  /// as described in the ACPI Specification 6.5.
  public var ccelAcpiTable: Foundation.Data = Foundation.Data()

  /// Optional. The CCEL event log. Formatted as described in the UEFI 2.10.
  public var ccelData: Foundation.Data = Foundation.Data()

  /// Optional. An Event Log containing additional events measured into the RTMR
  /// that are not already present in the CCEL.
  public var canonicalEventLog: Foundation.Data = Foundation.Data()

  /// Optional. The TDX attestation quote from the guest. It contains the RTMR
  /// values.
  public var tdQuote: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TdxCcelAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TdxCcelAttestation().with { $0.ccelAcpiTable = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let ccelAcpiTable = CodingKeys(stringValue: "ccelAcpiTable")
    static let ccelData = CodingKeys(stringValue: "ccelData")
    static let canonicalEventLog = CodingKeys(stringValue: "canonicalEventLog")
    static let tdQuote = CodingKeys(stringValue: "tdQuote")

    static let _knownKeys: Set<Swift.String> = [
      "ccelAcpiTable",
      "ccelData",
      "canonicalEventLog",
      "tdQuote",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .ccelAcpiTable) {
      self.ccelAcpiTable = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .ccelData) {
      self.ccelData = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .canonicalEventLog) {
      self.canonicalEventLog = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .tdQuote) {
      self.tdQuote = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ccelAcpiTable, forKey: .ccelAcpiTable)
    try container.encode(self.ccelData, forKey: .ccelData)
    try container.encode(self.canonicalEventLog, forKey: .canonicalEventLog)
    try container.encode(self.tdQuote, forKey: .tdQuote)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TdxCcelAttestation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
