// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Options to modify claims in the token to generate custom-purpose tokens.
public struct TokenOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Optional string to issue the token with a custom audience claim.
  /// Required if one or more nonces are specified.
  public var audience: Swift.String = Swift.String()

  /// Optional. Optional parameter to place one or more nonces in the eat_nonce
  /// claim in the output token. The minimum size for JSON-encoded EATs is 10
  /// bytes and the maximum size is 74 bytes.
  public var nonce: [Swift.String] = []

  /// Optional. Optional token type to select what type of token to return.
  public var tokenType: TokenType = TokenType()

  /// An optional additional configuration per token type.
  public var tokenTypeOptions: TokenTypeOptionsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TokenOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TokenOptions().with { $0.awsPrincipalTagsOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let awsPrincipalTagsOptions = CodingKeys(stringValue: "awsPrincipalTagsOptions")
    static let audience = CodingKeys(stringValue: "audience")
    static let nonce = CodingKeys(stringValue: "nonce")
    static let tokenType = CodingKeys(stringValue: "tokenType")

    static let _knownKeys: Set<Swift.String> = [
      "awsPrincipalTagsOptions",
      "audience",
      "nonce",
      "tokenType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .audience) {
      self.audience = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .nonce) {
      self.nonce = value
    }
    if let value = try container.decodeIfPresent(TokenType.self, forKey: .tokenType) {
      self.tokenType = value
    }

    var tokenTypeOptions: TokenTypeOptionsOneOf? = nil
    let tokenTypeOptionsCheckAndSet = {
      if tokenTypeOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'tokenTypeOptions'"))
      }
      tokenTypeOptions = $0
    }
    if let awsPrincipalTagsOptions = try container.decodeIfPresent(
      AwsPrincipalTagsOptions?.self, forKey: .awsPrincipalTagsOptions)
    {
      try tokenTypeOptionsCheckAndSet(.awsPrincipalTagsOptions(awsPrincipalTagsOptions))
    }
    self.tokenTypeOptions = tokenTypeOptions
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.audience, forKey: .audience)
    try container.encode(self.nonce, forKey: .nonce)
    try container.encode(self.tokenType, forKey: .tokenType)

    if let choice = self.tokenTypeOptions {
      switch choice {
      case .awsPrincipalTagsOptions(let value):
        try container.encode(value, forKey: .awsPrincipalTagsOptions)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An optional additional configuration per token type.
  public enum TokenTypeOptionsOneOf: Codable, Equatable, Sendable {
    /// Optional. Options for AWS token type.
    indirect case awsPrincipalTagsOptions(AwsPrincipalTagsOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TokenOptions"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
