// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Options to modify claims in the token to generate custom-purpose tokens.
public struct TokenOptions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Optional string to issue the token with a custom audience claim.
  /// Required if one or more nonces are specified.
  public var audience: Swift.String = Swift.String()

  /// Optional. Optional parameter to place one or more nonces in the eat_nonce
  /// claim in the output token. The minimum size for JSON-encoded EATs is 10
  /// bytes and the maximum size is 74 bytes.
  public var nonce: [Swift.String] = []

  /// Optional. Optional token type to select what type of token to return.
  public var tokenType: TokenType = TokenType()

  /// An optional additional configuration per token type.
  public var tokenTypeOptions: OneOf_TokenTypeOptions? = nil

  /// Initialize a new instance of `TokenOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TokenOptions().with { $0.awsPrincipalTagsOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case awsPrincipalTagsOptions = "awsPrincipalTagsOptions"
    case audience = "audience"
    case nonce = "nonce"
    case tokenType = "tokenType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.audience = try container.decode(Swift.String.self, forKey: .audience)
    self.nonce = try container.decode([Swift.String].self, forKey: .nonce)
    self.tokenType = try container.decode(TokenType.self, forKey: .tokenType)

    var tokenTypeOptions: OneOf_TokenTypeOptions? = nil
    let tokenTypeOptionsCheckAndSet = {
      if tokenTypeOptions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'tokenTypeOptions'"))
      }
      tokenTypeOptions = $0
    }
    if let awsPrincipalTagsOptions = try container.decodeIfPresent(
      AwsPrincipalTagsOptions?.self, forKey: .awsPrincipalTagsOptions)
    {
      try tokenTypeOptionsCheckAndSet(.awsPrincipalTagsOptions(awsPrincipalTagsOptions))
    }
    self.tokenTypeOptions = tokenTypeOptions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.audience, forKey: .audience)
    try container.encode(self.nonce, forKey: .nonce)
    try container.encode(self.tokenType, forKey: .tokenType)

    if let choice = self.tokenTypeOptions {
      switch choice {
      case .awsPrincipalTagsOptions(let value):
        try container.encode(value, forKey: .awsPrincipalTagsOptions)
      }
    }
  }

  /// An optional additional configuration per token type.
  public enum OneOf_TokenTypeOptions: Codable, Equatable, Sendable {
    /// Optional. Options for AWS token type.
    indirect case awsPrincipalTagsOptions(AwsPrincipalTagsOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TokenOptions"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
