// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// TPM2 data containing everything necessary to validate any platform state
/// measured into the TPM.
public struct TpmAttestation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// TPM2 PCR Quotes generated by calling TPM2_Quote on each PCR bank.
  public var quotes: [TpmAttestation.Quote] = []

  /// The binary TCG Event Log containing events measured into the TPM by the
  /// platform firmware and operating system. Formatted as described in the
  /// "TCG PC Client Platform Firmware Profile Specification".
  public var tcgEventLog: Foundation.Data = Foundation.Data()

  /// An Event Log containing additional events measured into the TPM that are
  /// not already present in the tcg_event_log. Formatted as described in the
  /// "Canonical Event Log Format" TCG Specification.
  public var canonicalEventLog: Foundation.Data = Foundation.Data()

  /// DER-encoded X.509 certificate of the Attestation Key (otherwise known as
  /// an AK or a TPM restricted signing key) used to generate the quotes.
  public var akCert: Foundation.Data = Foundation.Data()

  /// List of DER-encoded X.509 certificates which, together with the ak_cert,
  /// chain back to a trusted Root Certificate.
  public var certChain: [Foundation.Data] = []

  /// Initialize a new instance of `TpmAttestation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TpmAttestation().with { $0.quotes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information about Platform Control Registers (PCRs) including a signature
  /// over their values, which can be used for remote validation.
  public struct Quote: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The hash algorithm of the PCR bank being quoted, encoded as a TPM_ALG_ID
    public var hashAlgo: Swift.Int32 = Swift.Int32()

    /// Raw binary values of each PCRs being quoted.
    public var pcrValues: [Swift.Int32: Foundation.Data] = [:]

    /// TPM2 quote, encoded as a TPMS_ATTEST
    public var rawQuote: Foundation.Data = Foundation.Data()

    /// TPM2 signature, encoded as a TPMT_SIGNATURE
    public var rawSignature: Foundation.Data = Foundation.Data()

    /// Initialize a new instance of `Quote`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Quote().with { $0.hashAlgo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case hashAlgo = "hashAlgo"
      case pcrValues = "pcrValues"
      case rawQuote = "rawQuote"
      case rawSignature = "rawSignature"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.hashAlgo = try container.decode(Swift.Int32.self, forKey: .hashAlgo)
      self.pcrValues = try { () throws in
        let stringKeyed = try container.decode(
          [Swift.String: Foundation.Data].self, forKey: .pcrValues)
        let tuples = try stringKeyed.lazy.map {
          (key, value) throws -> (Swift.Int32, Foundation.Data) in
          guard let newKey = Swift.Int32(key) else {
            throw DecodingError.typeMismatch(
              Swift.Int32.self,
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Incorrect type for map key 'pcrValues'"))
          }
          return (newKey, value)
        }
        return Dictionary(uniqueKeysWithValues: tuples)
      }()
      self.rawQuote = try container.decode(Foundation.Data.self, forKey: .rawQuote)
      self.rawSignature = try container.decode(Foundation.Data.self, forKey: .rawSignature)
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.hashAlgo, forKey: .hashAlgo)
      do {
        let stringKeyed = Dictionary(
          uniqueKeysWithValues: self.pcrValues.lazy.map { (Swift.String($0), $1) }
        )
        try container.encode(stringKeyed, forKey: .pcrValues)
      }
      try container.encode(self.rawQuote, forKey: .rawQuote)
      try container.encode(self.rawSignature, forKey: .rawSignature)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TpmAttestation.Quote"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.TpmAttestation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
