// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A request for an attestation token, providing all the necessary information
/// needed for this service to verify Confidential GKE platform state of the
/// requestor.
public struct VerifyConfidentialGkeRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Challenge whose nonce was used to generate the
  /// attestation, in the format projects/*/locations/*/challenges/*. The
  /// provided Challenge will be consumed, and cannot be used again.
  public var challenge: Swift.String = Swift.String()

  /// Optional. A collection of fields that modify the token output.
  public var options: VerifyConfidentialGkeRequest.ConfidentialGkeOptions? = nil

  /// Optional. Optional platform security architecture hint for the verifier
  /// engine. Defaults to `VIRTUALIZED_CVM` behavior if unspecified.
  public var platformType: VerifyConfidentialGkeRequest.PlatformType =
    VerifyConfidentialGkeRequest.PlatformType()

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public var teeAttestation: OneOf_TeeAttestation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VerifyConfidentialGkeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VerifyConfidentialGkeRequest().with { $0.tpmAttestation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let tpmAttestation = CodingKeys(stringValue: "tpmAttestation")
    static let challenge = CodingKeys(stringValue: "challenge")
    static let options = CodingKeys(stringValue: "options")
    static let platformType = CodingKeys(stringValue: "platformType")

    static let _knownKeys: Set<Swift.String> = [
      "tpmAttestation",
      "challenge",
      "options",
      "platformType",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .challenge) {
      self.challenge = value
    }
    self.options = try container.decodeIfPresent(
      VerifyConfidentialGkeRequest.ConfidentialGkeOptions.self, forKey: .options)
    if let value = try container.decodeIfPresent(
      VerifyConfidentialGkeRequest.PlatformType.self, forKey: .platformType)
    {
      self.platformType = value
    }

    var teeAttestation: OneOf_TeeAttestation? = nil
    let teeAttestationCheckAndSet = {
      if teeAttestation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'teeAttestation'"))
      }
      teeAttestation = $0
    }
    if let tpmAttestation = try container.decodeIfPresent(
      TpmAttestation?.self, forKey: .tpmAttestation)
    {
      try teeAttestationCheckAndSet(.tpmAttestation(tpmAttestation))
    }
    self.teeAttestation = teeAttestation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.challenge, forKey: .challenge)
    try container.encodeIfPresent(self.options, forKey: .options)
    try container.encode(self.platformType, forKey: .platformType)

    if let choice = self.teeAttestation {
      switch choice {
      case .tpmAttestation(let value):
        try container.encode(value, forKey: .tpmAttestation)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Token options for Confidential GKE attestation.
  public struct ConfidentialGkeOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Optional string to issue the token with a custom audience
    /// claim. Required if custom nonces are specified.
    public var audience: Swift.String = Swift.String()

    /// Optional. Optional parameter to place one or more nonces in the eat_nonce
    /// claim in the output token. The minimum size for JSON-encoded EATs is 10
    /// bytes and the maximum size is 74 bytes.
    public var nonce: [Swift.String] = []

    /// Optional. Optional specification for how to sign the attestation token.
    /// Defaults to SIGNATURE_TYPE_OIDC if unspecified.
    public var signatureType: SignatureType = SignatureType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConfidentialGkeOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConfidentialGkeOptions().with { $0.audience = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let audience = CodingKeys(stringValue: "audience")
      static let nonce = CodingKeys(stringValue: "nonce")
      static let signatureType = CodingKeys(stringValue: "signatureType")

      static let _knownKeys: Set<Swift.String> = [
        "audience",
        "nonce",
        "signatureType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .audience) {
        self.audience = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .nonce) {
        self.nonce = value
      }
      if let value = try container.decodeIfPresent(SignatureType.self, forKey: .signatureType) {
        self.signatureType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.audience, forKey: .audience)
      try container.encode(self.nonce, forKey: .nonce)
      try container.encode(self.signatureType, forKey: .signatureType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialGkeRequest.ConfidentialGkeOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Platform types supported by Confidential GKE.
  /// This enum is not frozen, and new values may be added in the future.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PlatformType: Codable, Equatable, Sendable {
    /// Unspecified platform type, defaults to `VIRTUALIZED_CVM`.
    case unspecified
    /// Standard virtualized Confidential GKE VM.
    case virtualizedCvm
    /// Bare Metal host using a vTPM.
    case bareMetalVtpm
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .virtualizedCvm: return 1
      case .bareMetalVtpm: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PLATFORM_TYPE_UNSPECIFIED"
      case .virtualizedCvm: return "VIRTUALIZED_CVM"
      case .bareMetalVtpm: return "BARE_METAL_VTPM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PlatformType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PLATFORM_TYPE_UNSPECIFIED": self = .unspecified
      case "VIRTUALIZED_CVM": self = .virtualizedCvm
      case "BARE_METAL_VTPM": self = .bareMetalVtpm
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PlatformType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .virtualizedCvm
      case 2: self = .bareMetalVtpm
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PLATFORM_TYPE_UNSPECIFIED")
      case .virtualizedCvm: return try container.encode("VIRTUALIZED_CVM")
      case .bareMetalVtpm: return try container.encode("BARE_METAL_VTPM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public enum OneOf_TeeAttestation: Codable, Equatable, Sendable {
    /// The TPM-specific data provided by the attesting platform, used to
    /// populate any of the claims regarding platform state.
    indirect case tpmAttestation(TpmAttestation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialGkeRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
