// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A request for an attestation token, providing all the necessary information
/// needed for this service to verify the platform state of the requestor.
public struct VerifyConfidentialSpaceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the Challenge whose nonce was used to generate the
  /// attestation, in the format `projects/*/locations/*/challenges/*`. The
  /// provided Challenge will be consumed, and cannot be used again.
  public var challenge: Swift.String = Swift.String()

  /// Optional. Credentials used to populate the "emails" claim in the
  /// claims_token. If not present, token will not contain the "emails" claim.
  public var gcpCredentials: GcpCredentials? = nil

  /// Optional. A list of signed entities containing container image signatures
  /// that can be used for server-side signature verification.
  public var signedEntities: [SignedEntity] = []

  /// Optional. Information about the associated Compute Engine instance.
  /// Required for td_ccel requests only - tpm_attestation requests will provide
  /// this information in the attestation.
  public var gceShieldedIdentity: GceShieldedIdentity? = nil

  /// Optional. A collection of fields that modify the token output.
  public var options: VerifyConfidentialSpaceRequest.ConfidentialSpaceOptions? = nil

  /// Optional. An optional Nvidia attestation report, used to populate hardware
  /// rooted claims for Nvidia devices.
  public var nvidiaAttestation: NvidiaAttestation? = nil

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public var teeAttestation: OneOf_TeeAttestation? = nil

  /// Initialize a new instance of `VerifyConfidentialSpaceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VerifyConfidentialSpaceRequest().with { $0.tdCcel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tdCcel = "tdCcel"
    case tpmAttestation = "tpmAttestation"
    case challenge = "challenge"
    case gcpCredentials = "gcpCredentials"
    case signedEntities = "signedEntities"
    case gceShieldedIdentity = "gceShieldedIdentity"
    case options = "options"
    case nvidiaAttestation = "nvidiaAttestation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.challenge = try container.decode(Swift.String.self, forKey: .challenge)
    self.gcpCredentials = try container.decodeIfPresent(
      GcpCredentials.self, forKey: .gcpCredentials)
    self.signedEntities = try container.decode([SignedEntity].self, forKey: .signedEntities)
    self.gceShieldedIdentity = try container.decodeIfPresent(
      GceShieldedIdentity.self, forKey: .gceShieldedIdentity)
    self.options = try container.decodeIfPresent(
      VerifyConfidentialSpaceRequest.ConfidentialSpaceOptions.self, forKey: .options)
    self.nvidiaAttestation = try container.decodeIfPresent(
      NvidiaAttestation.self, forKey: .nvidiaAttestation)

    var teeAttestation: OneOf_TeeAttestation? = nil
    let teeAttestationCheckAndSet = {
      if teeAttestation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'teeAttestation'"))
      }
      teeAttestation = $0
    }
    if let tdCcel = try container.decodeIfPresent(TdxCcelAttestation?.self, forKey: .tdCcel) {
      try teeAttestationCheckAndSet(.tdCcel(tdCcel))
    }
    if let tpmAttestation = try container.decodeIfPresent(
      TpmAttestation?.self, forKey: .tpmAttestation)
    {
      try teeAttestationCheckAndSet(.tpmAttestation(tpmAttestation))
    }
    self.teeAttestation = teeAttestation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.challenge, forKey: .challenge)
    try container.encode(self.gcpCredentials, forKey: .gcpCredentials)
    try container.encode(self.signedEntities, forKey: .signedEntities)
    try container.encode(self.gceShieldedIdentity, forKey: .gceShieldedIdentity)
    try container.encode(self.options, forKey: .options)
    try container.encode(self.nvidiaAttestation, forKey: .nvidiaAttestation)

    if let choice = self.teeAttestation {
      switch choice {
      case .tdCcel(let value):
        try container.encode(value, forKey: .tdCcel)
      case .tpmAttestation(let value):
        try container.encode(value, forKey: .tpmAttestation)
      }
    }
  }

  /// Token options for Confidential Space attestation.
  public struct ConfidentialSpaceOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Optional string to issue the token with a custom audience
    /// claim. Required if custom nonces are specified.
    public var audience: Swift.String = Swift.String()

    /// Optional. Optional specification for token claims profile.
    public var tokenProfile: TokenProfile = TokenProfile()

    /// Optional. Optional parameter to place one or more nonces in the eat_nonce
    /// claim in the output token. The minimum size for JSON-encoded EATs is 10
    /// bytes and the maximum size is 74 bytes.
    public var nonce: [Swift.String] = []

    /// Optional. Optional specification for how to sign the attestation token.
    /// Defaults to SIGNATURE_TYPE_OIDC if unspecified.
    public var signatureType: SignatureType = SignatureType()

    /// An optional additional configuration per token type.
    public var tokenProfileOptions: OneOf_TokenProfileOptions? = nil

    /// Initialize a new instance of `ConfidentialSpaceOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConfidentialSpaceOptions().with { $0.awsPrincipalTagsOptions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case awsPrincipalTagsOptions = "awsPrincipalTagsOptions"
      case audience = "audience"
      case tokenProfile = "tokenProfile"
      case nonce = "nonce"
      case signatureType = "signatureType"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.audience = try container.decode(Swift.String.self, forKey: .audience)
      self.tokenProfile = try container.decode(TokenProfile.self, forKey: .tokenProfile)
      self.nonce = try container.decode([Swift.String].self, forKey: .nonce)
      self.signatureType = try container.decode(SignatureType.self, forKey: .signatureType)

      var tokenProfileOptions: OneOf_TokenProfileOptions? = nil
      let tokenProfileOptionsCheckAndSet = {
        if tokenProfileOptions != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'tokenProfileOptions'"))
        }
        tokenProfileOptions = $0
      }
      if let awsPrincipalTagsOptions = try container.decodeIfPresent(
        AwsPrincipalTagsOptions?.self, forKey: .awsPrincipalTagsOptions)
      {
        try tokenProfileOptionsCheckAndSet(.awsPrincipalTagsOptions(awsPrincipalTagsOptions))
      }
      self.tokenProfileOptions = tokenProfileOptions
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.audience, forKey: .audience)
      try container.encode(self.tokenProfile, forKey: .tokenProfile)
      try container.encode(self.nonce, forKey: .nonce)
      try container.encode(self.signatureType, forKey: .signatureType)

      if let choice = self.tokenProfileOptions {
        switch choice {
        case .awsPrincipalTagsOptions(let value):
          try container.encode(value, forKey: .awsPrincipalTagsOptions)
        }
      }
    }

    /// An optional additional configuration per token type.
    public enum OneOf_TokenProfileOptions: Codable, Equatable, Sendable {
      /// Optional. Options for the AWS token type.
      indirect case awsPrincipalTagsOptions(AwsPrincipalTagsOptions?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialSpaceRequest.ConfidentialSpaceOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public enum OneOf_TeeAttestation: Codable, Equatable, Sendable {
    /// Input only. A TDX with CCEL and RTMR Attestation Quote.
    indirect case tdCcel(TdxCcelAttestation?)
    /// Input only. The TPM-specific data provided by the attesting platform,
    /// used to populate any of the claims regarding platform state.
    indirect case tpmAttestation(TpmAttestation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialSpaceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
