// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A request for an attestation token, providing all the necessary information
/// needed for this service to verify Confidential GKE platform state of the
/// requestor.
public struct VerifyConfidentialGkeRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the Challenge whose nonce was used to generate the
  /// attestation, in the format projects/*/locations/*/challenges/*. The
  /// provided Challenge will be consumed, and cannot be used again.
  public var challenge: Swift.String = Swift.String()

  /// Optional. A collection of fields that modify the token output.
  public var options: VerifyConfidentialGkeRequest.ConfidentialGkeOptions? = nil

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public var teeAttestation: OneOf_TeeAttestation? = nil

  /// Initialize a new instance of `VerifyConfidentialGkeRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VerifyConfidentialGkeRequest().with { $0.tpmAttestation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tpmAttestation = "tpmAttestation"
    case challenge = "challenge"
    case options = "options"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.challenge = try container.decode(Swift.String.self, forKey: .challenge)
    self.options = try container.decodeIfPresent(
      VerifyConfidentialGkeRequest.ConfidentialGkeOptions.self, forKey: .options)

    var teeAttestation: OneOf_TeeAttestation? = nil
    let teeAttestationCheckAndSet = {
      if teeAttestation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'teeAttestation'"))
      }
      teeAttestation = $0
    }
    if let tpmAttestation = try container.decodeIfPresent(
      TpmAttestation?.self, forKey: .tpmAttestation)
    {
      try teeAttestationCheckAndSet(.tpmAttestation(tpmAttestation))
    }
    self.teeAttestation = teeAttestation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.challenge, forKey: .challenge)
    try container.encode(self.options, forKey: .options)

    if let choice = self.teeAttestation {
      switch choice {
      case .tpmAttestation(let value):
        try container.encode(value, forKey: .tpmAttestation)
      }
    }
  }

  /// Token options for Confidential GKE attestation.
  public struct ConfidentialGkeOptions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Optional string to issue the token with a custom audience
    /// claim. Required if custom nonces are specified.
    public var audience: Swift.String = Swift.String()

    /// Optional. Optional parameter to place one or more nonces in the eat_nonce
    /// claim in the output token. The minimum size for JSON-encoded EATs is 10
    /// bytes and the maximum size is 74 bytes.
    public var nonce: [Swift.String] = []

    /// Optional. Optional specification for how to sign the attestation token.
    /// Defaults to SIGNATURE_TYPE_OIDC if unspecified.
    public var signatureType: SignatureType = SignatureType()

    /// Initialize a new instance of `ConfidentialGkeOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConfidentialGkeOptions().with { $0.audience = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialGkeRequest.ConfidentialGkeOptions"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Required. A tee attestation report, used to populate hardware rooted
  /// claims.
  public enum OneOf_TeeAttestation: Codable, Equatable, Sendable {
    /// The TPM-specific data provided by the attesting platform, used to
    /// populate any of the claims regarding platform state.
    indirect case tpmAttestation(TpmAttestation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyConfidentialGkeRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
