// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A request for an attestation token, providing all the necessary information
/// needed for this service to verify the platform state of the requestor.
public struct VerifyAttestationRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the Challenge whose nonce was used to generate the
  /// attestation, in the format `projects/*/locations/*/challenges/*`. The
  /// provided Challenge will be consumed, and cannot be used again.
  public var challenge: Swift.String = Swift.String()

  /// Optional. Credentials used to populate the "emails" claim in the
  /// claims_token.
  public var gcpCredentials: GcpCredentials? = nil

  /// Required. The TPM-specific data provided by the attesting platform, used to
  /// populate any of the claims regarding platform state.
  public var tpmAttestation: TpmAttestation? = nil

  /// Optional. Optional information related to the Confidential Space TEE.
  public var confidentialSpaceInfo: ConfidentialSpaceInfo? = nil

  /// Optional. A collection of optional, workload-specified claims that modify
  /// the token output.
  public var tokenOptions: TokenOptions? = nil

  /// Optional. An optional indicator of the attester, only applies to certain
  /// products.
  public var attester: Swift.String = Swift.String()

  /// Optional. Optional resource link of the Compute Engine instance.
  /// Format:
  /// `projects/{project_number}/zones/{zone}/instances/{instance_id}`
  public var instance: Swift.String = Swift.String()

  /// An optional tee attestation report, used to populate hardware rooted
  /// claims.
  public var teeAttestation: OneOf_TeeAttestation? = nil

  /// An optional device attestation report.
  public var deviceAttestation: OneOf_DeviceAttestation? = nil

  /// Initialize a new instance of `VerifyAttestationRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VerifyAttestationRequest().with { $0.tdCcel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case tdCcel = "tdCcel"
    case sevSnpAttestation = "sevSnpAttestation"
    case nvidiaAttestation = "nvidiaAttestation"
    case challenge = "challenge"
    case gcpCredentials = "gcpCredentials"
    case tpmAttestation = "tpmAttestation"
    case confidentialSpaceInfo = "confidentialSpaceInfo"
    case tokenOptions = "tokenOptions"
    case attester = "attester"
    case instance = "instance"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.challenge = try container.decode(Swift.String.self, forKey: .challenge)
    self.gcpCredentials = try container.decodeIfPresent(
      GcpCredentials.self, forKey: .gcpCredentials)
    self.tpmAttestation = try container.decodeIfPresent(
      TpmAttestation.self, forKey: .tpmAttestation)
    self.confidentialSpaceInfo = try container.decodeIfPresent(
      ConfidentialSpaceInfo.self, forKey: .confidentialSpaceInfo)
    self.tokenOptions = try container.decodeIfPresent(TokenOptions.self, forKey: .tokenOptions)
    self.attester = try container.decode(Swift.String.self, forKey: .attester)
    self.instance = try container.decode(Swift.String.self, forKey: .instance)

    var teeAttestation: OneOf_TeeAttestation? = nil
    let teeAttestationCheckAndSet = {
      if teeAttestation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'teeAttestation'"))
      }
      teeAttestation = $0
    }
    if let tdCcel = try container.decodeIfPresent(TdxCcelAttestation?.self, forKey: .tdCcel) {
      try teeAttestationCheckAndSet(.tdCcel(tdCcel))
    }
    if let sevSnpAttestation = try container.decodeIfPresent(
      SevSnpAttestation?.self, forKey: .sevSnpAttestation)
    {
      try teeAttestationCheckAndSet(.sevSnpAttestation(sevSnpAttestation))
    }
    self.teeAttestation = teeAttestation

    var deviceAttestation: OneOf_DeviceAttestation? = nil
    let deviceAttestationCheckAndSet = {
      if deviceAttestation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'deviceAttestation'"))
      }
      deviceAttestation = $0
    }
    if let nvidiaAttestation = try container.decodeIfPresent(
      NvidiaAttestation?.self, forKey: .nvidiaAttestation)
    {
      try deviceAttestationCheckAndSet(.nvidiaAttestation(nvidiaAttestation))
    }
    self.deviceAttestation = deviceAttestation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.challenge, forKey: .challenge)
    try container.encode(self.gcpCredentials, forKey: .gcpCredentials)
    try container.encode(self.tpmAttestation, forKey: .tpmAttestation)
    try container.encode(self.confidentialSpaceInfo, forKey: .confidentialSpaceInfo)
    try container.encode(self.tokenOptions, forKey: .tokenOptions)
    try container.encode(self.attester, forKey: .attester)
    try container.encode(self.instance, forKey: .instance)

    if let choice = self.teeAttestation {
      switch choice {
      case .tdCcel(let value):
        try container.encode(value, forKey: .tdCcel)
      case .sevSnpAttestation(let value):
        try container.encode(value, forKey: .sevSnpAttestation)
      }
    }

    if let choice = self.deviceAttestation {
      switch choice {
      case .nvidiaAttestation(let value):
        try container.encode(value, forKey: .nvidiaAttestation)
      }
    }
  }

  /// An optional tee attestation report, used to populate hardware rooted
  /// claims.
  public enum OneOf_TeeAttestation: Codable, Equatable, Sendable {
    /// Optional. A TDX with CCEL and RTMR Attestation Quote.
    indirect case tdCcel(TdxCcelAttestation?)
    /// Optional. An SEV-SNP Attestation Report.
    indirect case sevSnpAttestation(SevSnpAttestation?)
  }

  /// An optional device attestation report.
  public enum OneOf_DeviceAttestation: Codable, Equatable, Sendable {
    /// Optional. An Nvidia attestation report for GPU and NVSwitch devices.
    indirect case nvidiaAttestation(NvidiaAttestation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.confidentialcomputing.v1.VerifyAttestationRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
